import Foundation

/// Supabase Auth client for Nissan GTR Auto iOS.
///
/// Password login, signup OTP verification and recovery enter through the
/// hardened Auth Edge. Supabase Auth remains the identity/session authority.
/// Apple/Google continue to use native Supabase Auth provider grants.
public final class GoTrueAuthClient: @unchecked Sendable {
    public struct Session: Sendable, Equatable {
        public let accessToken: String
        public let refreshToken: String?
        public let email: String?
        public let expiresIn: Int?
    }

    public struct SignupVerification: Sendable, Equatable {
        public let emailVerified: Bool
        public let phoneVerified: Bool?
        public let signupReady: Bool
    }

    public enum IdTokenProvider: String, Sendable {
        case apple
        case google
    }

    public static let preferredRedirectURL = "gtrcustomer://auth/callback"
    public static let legacyRedirectURL = "gtr-customer://auth/callback"
    public static let preferredCallbackScheme = "gtrcustomer"

    private let baseURL: URL
    private let anonKey: String
    private let session: URLSession

    public init(
        supabaseURL: String,
        anonKey: String,
        session: URLSession = .shared
    ) throws {
        let trimmed = supabaseURL.trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "/"))
        guard let url = URL(string: trimmed), !anonKey.isEmpty else {
            throw StorefrontError.notConfigured
        }
        self.baseURL = url
        self.anonKey = anonKey
        self.session = session
    }

    public convenience init() throws {
        try self.init(
            supabaseURL: AppEnv.supabaseURL,
            anonKey: AppEnv.supabaseAnonKey
        )
    }

    /// Email/password login through `auth-otp?action=complete_login`.
    public func signIn(email: String, password: String) async throws -> Session {
        let trimmedEmail = email.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedEmail.isEmpty, !password.isEmpty else {
            throw StorefrontError.message("Email and password are required.")
        }
        let obj = try await postEdge(
            function: "auth-otp",
            body: [
                "action": "complete_login",
                "email": trimmedEmail,
                "password": password,
            ]
        )
        return try parseEdgeSession(obj, fallbackEmail: trimmedEmail)
    }

    /// Start an email signup verification challenge generated by Supabase Auth.
    public func requestSignupEmailCode(email: String, fullName: String? = nil) async throws {
        let trimmedEmail = email.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedEmail.isEmpty else {
            throw StorefrontError.message("Email is required.")
        }
        var body: [String: Any] = [
            "action": "request",
            "channel": "email",
            "email": trimmedEmail,
        ]
        if let name = fullName?.trimmingCharacters(in: .whitespacesAndNewlines), !name.isEmpty {
            body["full_name"] = name
        }
        _ = try await postEdge(function: "auth-otp", body: body)
    }

    /// Verify the Supabase Auth-generated signup email OTP.
    public func verifySignupEmailCode(email: String, code: String) async throws -> SignupVerification {
        let trimmedEmail = email.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedCode = code.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedEmail.isEmpty, trimmedCode.count >= 6 else {
            throw StorefrontError.message("Email and verification code are required.")
        }
        let obj = try await postEdge(
            function: "auth-otp",
            body: [
                "action": "verify",
                "channel": "email",
                "email": trimmedEmail,
                "code": trimmedCode,
            ]
        )
        let verified = obj["verified"] as? [String: Any]
        return SignupVerification(
            emailVerified: verified?["email"] as? Bool == true,
            phoneVerified: verified?["phone"] as? Bool,
            signupReady: obj["signup_ready"] as? Bool == true
        )
    }

    /// Complete a verified pending Supabase Auth signup and receive its session.
    public func completeSignup(email: String, password: String, fullName: String? = nil) async throws -> Session {
        let trimmedEmail = email.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedEmail.isEmpty, password.count >= 8 else {
            throw StorefrontError.message("Email and a password of at least 8 characters are required.")
        }
        var body: [String: Any] = [
            "action": "complete_signup",
            "email": trimmedEmail,
            "password": password,
        ]
        if let name = fullName?.trimmingCharacters(in: .whitespacesAndNewlines), !name.isEmpty {
            body["full_name"] = name
        }
        let obj = try await postEdge(function: "auth-otp", body: body)
        return try parseEdgeSession(obj, fallbackEmail: trimmedEmail)
    }

    /// Non-enumerating Supabase Auth recovery request.
    public func requestPasswordReset(email: String) async throws {
        let trimmedEmail = email.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedEmail.isEmpty else {
            throw StorefrontError.message("Email is required.")
        }
        _ = try await postEdge(
            function: "request-password-reset",
            body: [
                "channel": "email",
                "email": trimmedEmail,
            ]
        )
    }

    /// Verify recovery OTP, update password inside the Supabase recovery session,
    /// and return the recovered session.
    public func completePasswordReset(email: String, code: String, newPassword: String) async throws -> Session {
        let trimmedEmail = email.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedCode = code.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedEmail.isEmpty, trimmedCode.count >= 6, newPassword.count >= 8 else {
            throw StorefrontError.message("Email, recovery code and a password of at least 8 characters are required.")
        }
        let obj = try await postEdge(
            function: "verify-password-reset",
            body: [
                "channel": "email",
                "email": trimmedEmail,
                "code": trimmedCode,
                "new_password": newPassword,
            ]
        )
        return try parseEdgeSession(obj, fallbackEmail: trimmedEmail)
    }

    /// Native Apple / Google ID token → Supabase Auth session.
    public func signInWithIdToken(
        provider: IdTokenProvider,
        idToken: String,
        nonce: String?
    ) async throws -> Session {
        let trimmed = idToken.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            throw StorefrontError.message("ID token is required.")
        }
        var body: [String: Any] = [
            "provider": provider.rawValue,
            "id_token": trimmed,
        ]
        if let nonce, !nonce.isEmpty { body["nonce"] = nonce }
        return try await postToken(grantType: "id_token", body: body, fallbackEmail: nil)
    }

    public func oauthAuthorizeURL(
        provider: IdTokenProvider,
        codeChallenge: String,
        redirectTo: String = GoTrueAuthClient.preferredRedirectURL
    ) throws -> URL {
        var components = URLComponents(
            url: baseURL.appendingPathComponent("auth/v1/authorize"),
            resolvingAgainstBaseURL: false
        )!
        components.queryItems = [
            URLQueryItem(name: "provider", value: provider.rawValue),
            URLQueryItem(name: "redirect_to", value: redirectTo),
            URLQueryItem(name: "code_challenge", value: codeChallenge),
            URLQueryItem(name: "code_challenge_method", value: "s256"),
        ]
        guard let url = components.url else {
            throw StorefrontError.message("Invalid GoTrue authorize URL.")
        }
        return url
    }

    public func exchangePKCE(authCode: String, codeVerifier: String) async throws -> Session {
        let code = authCode.trimmingCharacters(in: .whitespacesAndNewlines)
        let verifier = codeVerifier.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !code.isEmpty, !verifier.isEmpty else {
            throw StorefrontError.message("OAuth code and verifier are required.")
        }
        return try await postToken(
            grantType: "pkce",
            body: ["auth_code": code, "code_verifier": verifier],
            fallbackEmail: nil
        )
    }

    public static func parseAuthCallback(_ url: URL) -> AuthCallbackPayload? {
        guard isAuthCallbackURL(url) else { return nil }
        let items = queryAndFragmentItems(url)
        if let code = items["code"], !code.isEmpty { return .pkce(code: code) }
        if let access = items["access_token"], !access.isEmpty {
            let refresh = items["refresh_token"]
            let email = items["email"]
            let expires = items["expires_in"].flatMap(Int.init)
            return .session(
                Session(
                    accessToken: access,
                    refreshToken: (refresh?.isEmpty == false) ? refresh : nil,
                    email: (email?.isEmpty == false) ? email : nil,
                    expiresIn: expires
                )
            )
        }
        if let err = items["error_description"] ?? items["error"] { return .error(err) }
        return nil
    }

    public static func isAuthCallbackURL(_ url: URL) -> Bool {
        let scheme = (url.scheme ?? "").lowercased()
        guard scheme == "gtrcustomer" || scheme == "gtr-customer" else { return false }
        let host = (url.host ?? "").lowercased()
        let path = url.path.trimmingCharacters(in: CharacterSet(charactersIn: "/")).lowercased()
        if host == "auth" && (path == "callback" || path.isEmpty || path.hasPrefix("callback")) { return true }
        if host.isEmpty && (path == "auth/callback" || path.hasPrefix("auth/callback")) { return true }
        return false
    }

    // MARK: - Edge internals

    private func postEdge(function: String, body: [String: Any]) async throws -> [String: Any] {
        let url = baseURL.appendingPathComponent("functions/v1/\(function)")
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(anonKey, forHTTPHeaderField: "apikey")
        request.setValue("Bearer \(anonKey)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            throw StorefrontError.message("Invalid authentication response.")
        }
        guard let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw StorefrontError.message("Authentication service returned non-JSON (HTTP \(http.statusCode)).")
        }
        if !(200 ..< 300).contains(http.statusCode) || obj["ok"] as? Bool == false || obj["error"] != nil {
            let desc = (obj["error"] as? String) ?? (obj["message"] as? String) ?? "HTTP \(http.statusCode)"
            let code = obj["code"] as? String
            throw StorefrontError.message(code.map { "\(desc) [\($0)]" } ?? desc)
        }
        return obj
    }

    private func parseEdgeSession(_ obj: [String: Any], fallbackEmail: String?) throws -> Session {
        guard let access = obj["access_token"] as? String, !access.isEmpty else {
            throw StorefrontError.message("Auth Edge response missing access_token.")
        }
        let refresh = obj["refresh_token"] as? String
        return Session(
            accessToken: access,
            refreshToken: (refresh?.isEmpty == false) ? refresh : nil,
            email: (obj["email"] as? String) ?? fallbackEmail,
            expiresIn: obj["expires_in"] as? Int
        )
    }

    private func postToken(
        grantType: String,
        body: [String: Any],
        fallbackEmail: String?
    ) async throws -> Session {
        var components = URLComponents(
            url: baseURL.appendingPathComponent("auth/v1/token"),
            resolvingAgainstBaseURL: false
        )!
        components.queryItems = [URLQueryItem(name: "grant_type", value: grantType)]
        guard let url = components.url else {
            throw StorefrontError.message("Invalid GoTrue token URL.")
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(anonKey, forHTTPHeaderField: "apikey")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            throw StorefrontError.message("Invalid HTTP response.")
        }
        guard let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw StorefrontError.message("GoTrue returned non-JSON (HTTP \(http.statusCode)).")
        }
        if !(200 ..< 300).contains(http.statusCode) {
            let desc = (obj["error_description"] as? String)
                ?? (obj["msg"] as? String)
                ?? (obj["error"] as? String)
                ?? "HTTP \(http.statusCode)"
            throw StorefrontError.message(desc)
        }
        guard let access = obj["access_token"] as? String, !access.isEmpty else {
            throw StorefrontError.message("GoTrue response missing access_token.")
        }
        let refresh = obj["refresh_token"] as? String
        var userEmail = fallbackEmail
        if let user = obj["user"] as? [String: Any],
           let fromUser = user["email"] as? String,
           !fromUser.isEmpty {
            userEmail = fromUser
        }
        return Session(
            accessToken: access,
            refreshToken: (refresh?.isEmpty == false) ? refresh : nil,
            email: userEmail,
            expiresIn: obj["expires_in"] as? Int
        )
    }

    private static func queryAndFragmentItems(_ url: URL) -> [String: String] {
        var out: [String: String] = [:]
        if let items = URLComponents(url: url, resolvingAgainstBaseURL: false)?.queryItems {
            for item in items { if let value = item.value { out[item.name] = value } }
        }
        if let fragment = url.fragment, !fragment.isEmpty {
            for pair in fragment.split(separator: "&") {
                let parts = pair.split(separator: "=", maxSplits: 1).map(String.init)
                guard parts.count == 2 else { continue }
                out[parts[0]] = parts[1].removingPercentEncoding ?? parts[1]
            }
        }
        return out
    }
}

public enum AuthCallbackPayload: Sendable {
    case pkce(code: String)
    case session(GoTrueAuthClient.Session)
    case error(String)
}
