-- Our hooks on Supabase-managed schemas (not in a dump of public/private): storage policies from
-- hosted (delivery-pods, catalogue buckets ...) and the trigger that creates a profile per Auth user.
SET client_min_messages = warning;
DROP POLICY IF EXISTS "catalog_diagrams_staff_delete" ON storage."objects"; CREATE POLICY "catalog_diagrams_staff_delete" ON storage."objects" AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'catalog-diagrams'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role])));
DROP POLICY IF EXISTS "catalog_diagrams_public_read" ON storage."objects"; CREATE POLICY "catalog_diagrams_public_read" ON storage."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'catalog-diagrams'::text));
DROP POLICY IF EXISTS "catalog_diagrams_staff_insert" ON storage."objects"; CREATE POLICY "catalog_diagrams_staff_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'catalog-diagrams'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role])));
DROP POLICY IF EXISTS "catalog_diagrams_staff_update" ON storage."objects"; CREATE POLICY "catalog_diagrams_staff_update" ON storage."objects" AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'catalog-diagrams'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role]))) WITH CHECK (((bucket_id = 'catalog-diagrams'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role])));
DROP POLICY IF EXISTS "payslips_storage_select" ON storage."objects"; CREATE POLICY "payslips_storage_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO authenticated USING (((bucket_id = 'payslips'::text) AND (has_staff_role(ARRAY['admin'::staff_role, 'hr'::staff_role]) OR (EXISTS ( SELECT 1
   FROM (payslips ps
     JOIN employees e ON ((e.id = ps.employee_id)))
  WHERE ((ps.storage_path = objects.name) AND (e.user_id = auth.uid())))))));
DROP POLICY IF EXISTS "payslips_storage_insert" ON storage."objects"; CREATE POLICY "payslips_storage_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'payslips'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'hr'::staff_role])));
DROP POLICY IF EXISTS "payslips_storage_update" ON storage."objects"; CREATE POLICY "payslips_storage_update" ON storage."objects" AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'payslips'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'hr'::staff_role]))) WITH CHECK (((bucket_id = 'payslips'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'hr'::staff_role])));
DROP POLICY IF EXISTS "payslips_storage_delete" ON storage."objects"; CREATE POLICY "payslips_storage_delete" ON storage."objects" AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'payslips'::text) AND has_staff_role(ARRAY['admin'::staff_role])));
DROP POLICY IF EXISTS "delivery_pods_storage_insert" ON storage."objects"; CREATE POLICY "delivery_pods_storage_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'delivery-pods'::text) AND _can_write_delivery_pod_object(name)));
DROP POLICY IF EXISTS "customer_receipts_storage_select" ON storage."objects"; CREATE POLICY "customer_receipts_storage_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO authenticated USING (((bucket_id = 'customer-receipts'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'sales'::staff_role, 'finance'::staff_role])));
DROP POLICY IF EXISTS "delivery_pods_storage_select" ON storage."objects"; CREATE POLICY "delivery_pods_storage_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO authenticated USING (((bucket_id = 'delivery-pods'::text) AND _can_select_delivery_pod_object(name)));
DROP POLICY IF EXISTS "delivery_pods_storage_update" ON storage."objects"; CREATE POLICY "delivery_pods_storage_update" ON storage."objects" AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'delivery-pods'::text) AND _can_write_delivery_pod_object(name))) WITH CHECK (((bucket_id = 'delivery-pods'::text) AND _can_write_delivery_pod_object(name)));
DROP POLICY IF EXISTS "delivery_pods_storage_delete" ON storage."objects"; CREATE POLICY "delivery_pods_storage_delete" ON storage."objects" AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'delivery-pods'::text) AND has_staff_role(ARRAY['admin'::staff_role])));
DROP POLICY IF EXISTS "review_photos_storage_select" ON storage."objects"; CREATE POLICY "review_photos_storage_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO authenticated USING (((bucket_id = 'review-photos'::text) AND _can_select_review_photo_object(name)));
DROP POLICY IF EXISTS "review_photos_storage_insert" ON storage."objects"; CREATE POLICY "review_photos_storage_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'review-photos'::text) AND _can_write_review_photo_object(name)));
DROP POLICY IF EXISTS "review_photos_storage_update" ON storage."objects"; CREATE POLICY "review_photos_storage_update" ON storage."objects" AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'review-photos'::text) AND _can_write_review_photo_object(name))) WITH CHECK (((bucket_id = 'review-photos'::text) AND _can_write_review_photo_object(name)));
DROP POLICY IF EXISTS "review_photos_storage_delete" ON storage."objects"; CREATE POLICY "review_photos_storage_delete" ON storage."objects" AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'review-photos'::text) AND _can_write_review_photo_object(name)));
DROP POLICY IF EXISTS "procurement_invoices_staff_select" ON storage."objects"; CREATE POLICY "procurement_invoices_staff_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO authenticated USING (((bucket_id = 'procurement-invoices'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role, 'finance'::staff_role])));
DROP POLICY IF EXISTS "procurement_invoices_staff_insert" ON storage."objects"; CREATE POLICY "procurement_invoices_staff_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'procurement-invoices'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role, 'finance'::staff_role])));
DROP POLICY IF EXISTS "procurement_invoices_staff_update" ON storage."objects"; CREATE POLICY "procurement_invoices_staff_update" ON storage."objects" AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'procurement-invoices'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role, 'finance'::staff_role]))) WITH CHECK (((bucket_id = 'procurement-invoices'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'warehouse'::staff_role, 'finance'::staff_role])));
DROP POLICY IF EXISTS "procurement_invoices_admin_delete" ON storage."objects"; CREATE POLICY "procurement_invoices_admin_delete" ON storage."objects" AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'procurement-invoices'::text) AND has_staff_role(ARRAY['admin'::staff_role])));
DROP POLICY IF EXISTS "product_images_storage_select" ON storage."objects"; CREATE POLICY "product_images_storage_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'product-images'::text));
DROP POLICY IF EXISTS "product_images_storage_insert" ON storage."objects"; CREATE POLICY "product_images_storage_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'product-images'::text) AND _can_write_product_image_object(name)));
DROP POLICY IF EXISTS "product_images_storage_update" ON storage."objects"; CREATE POLICY "product_images_storage_update" ON storage."objects" AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'product-images'::text) AND _can_write_product_image_object(name))) WITH CHECK (((bucket_id = 'product-images'::text) AND _can_write_product_image_object(name)));
DROP POLICY IF EXISTS "product_images_storage_delete" ON storage."objects"; CREATE POLICY "product_images_storage_delete" ON storage."objects" AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'product-images'::text) AND _can_write_product_image_object(name)));
DROP POLICY IF EXISTS "petty_cash_receipts_storage_select" ON storage."objects"; CREATE POLICY "petty_cash_receipts_storage_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO authenticated USING (((bucket_id = 'petty-cash-receipts'::text) AND _can_access_petty_cash_receipt_object(name)));
DROP POLICY IF EXISTS "petty_cash_receipts_storage_insert" ON storage."objects"; CREATE POLICY "petty_cash_receipts_storage_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'petty-cash-receipts'::text) AND _can_access_petty_cash_receipt_object(name)));
DROP POLICY IF EXISTS "petty_cash_receipts_storage_delete" ON storage."objects"; CREATE POLICY "petty_cash_receipts_storage_delete" ON storage."objects" AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'petty-cash-receipts'::text) AND has_staff_role(ARRAY['admin'::staff_role, 'finance'::staff_role])));
DROP POLICY IF EXISTS "staff_signatures_own_insert" ON storage."objects"; CREATE POLICY "staff_signatures_own_insert" ON storage."objects" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'staff-signatures'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text) AND (is_pos_approver() OR has_staff_role(ARRAY['admin'::staff_role, 'finance'::staff_role]))));
DROP POLICY IF EXISTS "staff_signatures_own_update" ON storage."objects"; CREATE POLICY "staff_signatures_own_update" ON storage."objects" AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'staff-signatures'::text) AND (owner_id = (( SELECT auth.uid() AS uid))::text))) WITH CHECK (((bucket_id = 'staff-signatures'::text) AND ((storage.foldername(name))[1] = (( SELECT auth.uid() AS uid))::text)));
DROP POLICY IF EXISTS "staff_signatures_own_select" ON storage."objects"; CREATE POLICY "staff_signatures_own_select" ON storage."objects" AS PERMISSIVE FOR SELECT TO authenticated USING (((bucket_id = 'staff-signatures'::text) AND ((owner_id = (( SELECT auth.uid() AS uid))::text) OR has_staff_role(ARRAY['admin'::staff_role, 'finance'::staff_role]))));
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
