import sqlite3
c = sqlite3.connect("crawler_state.db")
p = sqlite3.connect("out/cache_parse_state.db")
print("=== CRAWL ===")
for s,n in c.execute("SELECT status,COUNT(*) FROM queue GROUP BY status ORDER BY 2 DESC"): print(f"  {s}: {n}")
v = c.execute("SELECT SUM(status='VISITED'), SUM(status='PENDING'), SUM(status='BLOCKED_CF'), SUM(status='PROCESSING') FROM queue WHERE url LIKE '%/vehicle%'").fetchone()
print(f"vehicle visited/pending/processing: {v[0]}/{v[1]}/{v[3]}")
last = c.execute("SELECT updated_at FROM queue WHERE status='VISITED' ORDER BY updated_at DESC LIMIT 1").fetchone()
print(f"last VISITED: {last[0] if last else 'n/a'}")
print(f"scraped_data: {c.execute('SELECT COUNT(*) FROM scraped_data').fetchone()[0]}")
print("=== PARSE ===")
for s,n in p.execute("SELECT status,COUNT(*) FROM parse_queue GROUP BY status ORDER BY 2 DESC"): print(f"  {s}: {n}")
